# Generated by Django 3.2.4 on 2021-06-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.group'),
        ),
    ]
